enhavo_media_theme_file:
    path:  /media/file/{id}/{shortMd5Checksum}/{filename}
    methods: [GET]
    defaults:
        _expose: [theme]
        _endpoint:
            type: media_file
            find_by: [id, filename]
            checksum_test: true
            checksum_parameter: shortMd5Checksum
