admin:
    prefix: /admin
    resource: routes/admin/*

admin_api:
    prefix: /admin/api
    resource: routes/admin_api/*

app:
    resource: ../src/App/Controller
    type: annotation

endpoint:
    resource: ../src/App/Endpoint
    type: endpoint
