app_admin_person_index:
    path: /person/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: app_admin_api_person_index
        _endpoint:
            type: admin

app_admin_person_create:
    path: /person/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: app_admin_api_person_create
        _endpoint:
            type: admin

app_admin_person_update:
    path: /person/update/{id}
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: app_admin_api_person_update
        _endpoint:
            type: admin
